### ISSUE TITLE
[JOSS review] Examples in README fail

### ISSUE THREAD

**Issue by janfreyberg** [Saran-nns/sorn#29]
Hi there,

I was just trying to run the examples as provided in the README, but ran into an error:

```python
from sorn import Simulator
import numpy as np

# Sample input
num_features = 10
time_steps = 200
inputs = np.random.rand(num_features,time_steps)

# To simulate the network;
matrices_dict, Exc_activity, Inh_activity, Rec_activity, num_active_connections = Simulator.simulate_sorn(inputs = inputs, phase='plasticity', matrices=None, noise = True, time_steps=time_steps, _ne = 200, _nu=num_features)

# To resume the simulation, load the matrices_dict from previous simulation;
matrices_dict, Exc_activity, Inh_activity, Rec_activity, num_active_connections = Simulator.simulate_sorn(inputs = inputs, phase='plasticity', matrices=matrices_dict, noise= True, time_steps=time_steps,_ne = 200, _nu=num_features)
```

Produces the following error:
```
Network Initialized
Number of connections in Wee 3881 , Wei 1584, Wie 8000
Shapes Wee (200, 200) Wei (40, 200) Wie (200, 40)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-3e49ac279123> in <module>
      8
      9 # To simulate the network;
---> 10 matrices_dict, Exc_activity, Inh_activity, Rec_activity, num_active_connections = Simulator.simulate_sorn(inputs = inputs, phase='plasticity', matrices=None, noise = True, time_steps=time_steps, _ne = 200, _nu=num_features)
     11
     12 # To resume the simulation, load the matrices_dict from previous simulation;

~/github/joss-reviews/.venv/lib/python3.9/site-packages/sorn/sorn.py in simulate_sorn(self, inputs, phase, matrices, time_steps, noise, freeze, **kwargs)
    956
    957             # STDP
--> 958             if 'stdp' not in self.freeze:
    959                 Wee_t = plasticity.stdp(
    960                     Wee[i], x_buffer, cutoff_weights=(0.0, 1.0))

TypeError: argument of type 'NoneType' is not iterable
```

I assume this is a relatively easy fix for the `freeze` attribute?

Thanks

_this is part of the review: https://github.com/openjournals/joss-reviews/issues/3545_

**Comment by janfreyberg** [comment]
Note that when I try to provide an argument for `freeze`, I also encounter errors:

```python
matrices_dict, Exc_activity, Inh_activity, Rec_activity, num_active_connections = Simulator.simulate_sorn(
    inputs = inputs, phase='plasticity', matrices=None, noise = True,
    time_steps=time_steps, _ne = 200, _nu=num_features,
    freeze=['ip'])

Network Initialized
Number of connections in Wee 3904 , Wei 1569, Wie 8000
Shapes Wee (200, 200) Wei (40, 200) Wie (200, 40)
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-4-8c54dfffe88b> in <module>
      8
      9 # To simulate the network;
---> 10 matrices_dict, Exc_activity, Inh_activity, Rec_activity, num_active_connections = Simulator.simulate_sorn(inputs = inputs, phase='plasticity', matrices=None, noise = True, time_steps=time_steps, _ne = 200, _nu=num_features, freeze=['ip'])

~/github/joss-reviews/.venv/lib/python3.9/site-packages/sorn/sorn.py in simulate_sorn(self, inputs, phase, matrices, time_steps, noise, freeze, **kwargs)
    981             # Assign the matrices to the matrix collections
    982             matrix_collection.weight_matrix(Wee_t, Wei_t, Wie[i], i)
--> 983             matrix_collection.threshold_matrix(Te_t, Ti[i], i)
    984             matrix_collection.network_activity_t(x_buffer, y_buffer, i)
    985

UnboundLocalError: local variable 'Te_t' referenced before assignment
```

**Comment by janfreyberg** [comment]
I should note that I am currently using the latest install from github, but the first error also occurred on the version in PyPi!

**Comment by Saran-nns** [comment]
Hi @janfreyberg. Thank you for reporting the issue. The variable assignment and the freeze options are fixed. The github repo and the pypi (v0.5.2) are also updated. Test runs of README examples are done at [colab notebook](https://colab.research.google.com/drive/1qz_Xkfam0wCCu2pz2kFogEJDWU2ED8Q4#scrollTo=xpHqf0bijR_d)
 Thank you :)

**Comment by janfreyberg** [comment]
Thanks @Saran-nns (and sorry for the delay) - I can run the examples from that notebook, but the following from the README seems to still fail:

```python
matrices_dict, Exc_activity, Inh_activity, Rec_activity, num_active_connections = Simulator.simulate_sorn(inputs = inputs, phase='plasticity', matrices=None, noise = True, time_steps=time_steps, _ne = 200, _nu=num_features, freeze=['ip'])
```

Seems like the main difference between this and your colab is the `time_steps` argument, which is set to `time_steps` in the README, but 1 in the colab.

Can you clarify whether this should work as is in the readme and fix a bug if so - or change the readme otherwise?

You might also want to use some way of testing your README examples automatically. This library could help with that:
https://github.com/koaning/mktestdocs
